/* Core Physio Clinic — bilingual content (EN/AR) + structured data. */

const NAV = [
  { id: 'home',     en: 'Home',         ar: 'الرئيسية' },
  { id: 'about',    en: 'About',        ar: 'عن العيادة' },
  { id: 'journey',  en: 'How It Works', ar: 'كيف نساعدك' },
  { id: 'services', en: 'Services',     ar: 'الخدمات' },
  { id: 'reviews',  en: 'Reviews',      ar: 'الآراء' },
  { id: 'location', en: 'Location',     ar: 'الموقع' },
];

const SERVICES = [
  { icon: 'activity',     en: 'Physiotherapy Sessions',          ar: 'جلسات العلاج الطبيعي',        den: 'Personalized one-on-one treatment to restore strength and mobility.', dar: 'علاج فردي مخصّص لاستعادة القوة والحركة.' },
  { icon: 'zap',          en: 'Sports Injury Rehabilitation',    ar: 'تأهيل إصابات الملاعب',         den: 'Evidence-based recovery to return athletes to peak performance.',    dar: 'تأهيل قائم على الأدلة لعودة الرياضيين لأفضل أداء.' },
  { icon: 'move-down',    en: 'Back Pain Treatment',             ar: 'علاج آلام الظهر',             den: 'Targeted therapy for chronic and acute lower-back pain.',            dar: 'علاج موجّه لآلام أسفل الظهر المزمنة والحادة.' },
  { icon: 'bone',         en: 'Neck Pain Treatment',             ar: 'علاج آلام الرقبة',            den: 'Relieve tension, stiffness and posture-related neck pain.',          dar: 'تخفيف التوتر والتيبّس وآلام الرقبة الناتجة عن وضعية الجسم.' },
  { icon: 'hand',         en: 'Manual Therapy',                  ar: 'العلاج اليدوي',               den: 'Hands-on mobilization to ease pain and improve movement.',           dar: 'تحريك يدوي لتخفيف الألم وتحسين الحركة.' },
  { icon: 'droplets',     en: 'Lymphedema Treatment',            ar: 'علاج الوذمة اللمفية',         den: 'Specialized drainage therapy to reduce swelling and discomfort.',    dar: 'علاج تصريف متخصّص لتقليل التورّم والانزعاج.' },
  { icon: 'stethoscope',  en: 'Post-Surgery Rehabilitation',     ar: 'التأهيل بعد الجراحة',         den: 'Structured recovery programs after orthopedic surgery.',             dar: 'برامج تعافٍ منظّمة بعد جراحات العظام.' },
  { icon: 'person-standing', en: 'Musculoskeletal Rehabilitation', ar: 'تأهيل الجهاز الحركي',      den: 'Restore function across joints, muscles and connective tissue.',     dar: 'استعادة وظيفة المفاصل والعضلات والأنسجة الضامة.' },
  { icon: 'scan-line',    en: 'Movement Assessment',             ar: 'تقييم الحركة',                den: 'Detailed analysis to find the root cause of your limitation.',       dar: 'تحليل دقيق لاكتشاف السبب الجذري لمحدودية حركتك.' },
  { icon: 'shield-plus',  en: 'Pain Management Programs',        ar: 'برامج إدارة الألم',           den: 'Long-term strategies to keep you active and pain-free.',             dar: 'استراتيجيات طويلة المدى لتبقى نشيطًا وبلا ألم.' },
];

const STEPS = [
  { n: '01', icon: 'clipboard-list', en: 'Assessment',           ar: 'التقييم',             den: 'We listen, examine and understand your condition in detail.',          dar: 'نستمع ونفحص ونفهم حالتك بالتفصيل.' },
  { n: '02', icon: 'route',          en: 'Personalized Plan',     ar: 'خطة مخصّصة',          den: 'A treatment plan built around your body, goals and lifestyle.',        dar: 'خطة علاج مبنية على جسمك وأهدافك ونمط حياتك.' },
  { n: '03', icon: 'activity',       en: 'Rehabilitation',        ar: 'بدء التأهيل',         den: 'Hands-on sessions using modern, evidence-based techniques.',           dar: 'جلسات عملية بأحدث التقنيات القائمة على الأدلة.' },
  { n: '04', icon: 'line-chart',     en: 'Monitor & Adjust',      ar: 'المتابعة والتعديل',   den: 'We track your progress and refine the plan as you improve.',           dar: 'نتابع تقدّمك ونحسّن الخطة مع تحسّنك.' },
  { n: '05', icon: 'trophy',         en: 'Back to Life',          ar: 'العودة للحياة',       den: 'Regain movement and return to the activities you love.',               dar: 'استعد حركتك وعد إلى الأنشطة التي تحبها.' },
];

const REVIEWS = [
  { name: 'Alaa Hassan',        ar_name: 'آلاء حسن',        rating: 5,
    en: 'I had a very good experience at this physiotherapy clinic. The clinic is extremely clean, well-organized, and the environment is very comfortable. The staff are friendly and professional.',
    ar: 'تجربة ممتازة في هذه العيادة. المكان نظيف جدًا ومنظّم والأجواء مريحة للغاية، والطاقم ودود ومحترف.' },
  { name: 'Iman Khaled',        ar_name: 'إيمان خالد',      rating: 5,
    en: 'Great management and very clean facility. Dr. Hadeel Ibrahim is amazing. She is professional, knowledgeable, and trustworthy.',
    ar: 'إدارة رائعة ومكان نظيف جدًا. د. هديل إبراهيم رائعة — محترفة وذات خبرة وأهل للثقة.' },
  { name: 'Esraa Alaa Hejazi',  ar_name: 'إسراء علاء حجازي', rating: 5,
    en: 'Dr. Alyaa was incredibly supportive and professional throughout my recovery journey. Highly recommended.',
    ar: 'د. علياء كانت داعمة ومحترفة بشكل كبير طوال رحلة تعافيي. أنصح بها بشدة.' },
];

const GALLERY = [
  { icon: 'armchair',       en: 'Reception Area',          ar: 'منطقة الاستقبال', tone: 'mint', img: '/assets/ChatGPT Image Jul 1, 2026, 02_07_04 PM.png' },
  { icon: 'bed',            en: 'Treatment Room',          ar: 'غرفة العلاج', tone: 'teal', img: '/assets/treatment-room.jpg' },
  { icon: 'dumbbell',       en: 'Rehabilitation Equipment', ar: 'أجهزة التأهيل', tone: 'soft', img: '/assets/hero2.jpg' },
  { icon: 'activity',       en: 'Rehabilitation Session',  ar: 'جلسة تأهيل', tone: 'teal', img: '/assets/ChatGPT Image Jun 22, 2026, 11_51_25 PM.png' },
  { icon: 'heart-handshake',en: 'Comfortable Environment', ar: 'بيئة مريحة', tone: 'soft', img: '/assets/vcdvgb.png' },
  { icon: 'users',          en: 'Professional Team',       ar: 'فريق محترف', tone: 'mint', img: '/assets/pexels-hannah-barata-776560167-27925505.jpg' },
];

const T = {
  en: {
    book: 'Book Appointment', whatsapp: 'Chat on WhatsApp', call: 'Call Now', directions: 'Get Directions',
    bookCta: 'Book on WhatsApp', learn: 'Learn More',
    ratingLabel: 'Google Rating', reviewsLabel: 'Patient Reviews',
    heroBadge: 'Physiotherapy & Rehabilitation · Sheikh Zayed',
    heroTitle: 'Your Journey Back to Pain-Free Living Starts Here.',
    heroSub: 'Professional physiotherapy and rehabilitation care in Sheikh Zayed designed to help you move better, recover faster, and regain confidence in your daily life.',
    trust1: 'Professional Rehabilitation Care', trust2: 'Modern Treatment Techniques',
    statPatients: 'Happy Patients', statOwned: 'Women-Owned Clinic', statLocated: 'Located in Sheikh Zayed', statRating: 'Rating',
    empathyEy: 'We understand', empathyTitle: 'Living With Pain Shouldn’t Be Your New Normal.',
    empathyBody: 'Whether you’re struggling with back pain, neck pain, sports injuries, posture issues, or limited movement, these challenges affect every aspect of daily life. At Core Physio Clinic, we understand that recovery is about more than treating pain — it’s about restoring your quality of life.',
    pains: ['Back & neck pain', 'Sports injuries', 'Posture problems', 'Limited movement', 'Post-surgery recovery', 'Chronic stiffness'],
    aboutEy: 'Meet the clinic', aboutTitle: 'A Place Built Around Your Recovery.',
    aboutBody: 'Located inside Twin Towers Mall in Sheikh Zayed, Core Physio Clinic provides a modern, comfortable, and welcoming environment where patients receive personalized treatment plans using evidence-based physiotherapy techniques.',
    aboutFeat: ['Women-owned clinic', 'Comfortable atmosphere', 'Modern rehabilitation approach', 'Patient-centered care'],
    trustEy: 'Why patients trust us', trustTitle: 'Trusted By Patients Across Sheikh Zayed.',
    trustSub: 'A reputation built on real results, genuine care, and a spotless, welcoming clinic.',
    trustItems: [
      { icon: 'star', t: '4.9 Google Rating', d: 'Rated 4.9 out of 5 across 35+ verified patient reviews.' },
      { icon: 'users', t: 'Professional Team', d: 'Experienced physiotherapists focused on long-term recovery.' },
      { icon: 'sparkles', t: 'Spotless Facility', d: 'Clean, organized and welcoming throughout.' },
      { icon: 'heart', t: 'Friendly Environment', d: 'Warm, supportive care from your first visit.' },
      { icon: 'clipboard-list', t: 'Personalized Treatments', d: 'Every plan is tailored to your body and goals.' },
      { icon: 'shield-check', t: 'Evidence-Based Care', d: 'Modern, proven rehabilitation techniques.' },
    ],
    journeyEy: 'How we help you recover', journeyTitle: 'Recovery Is a Journey, and We Guide Every Step.',
    journeySub: 'A clear, supportive path from your first assessment to a full return to daily life.',
    servicesEy: 'Our specialized services', servicesTitle: 'Care for Every Stage of Your Recovery.',
    servicesSub: 'From acute pain relief to long-term performance — comprehensive physiotherapy under one roof.',
    reviewsEy: 'Real stories from real patients', reviewsTitle: 'Recovery You Can Feel — and Patients Can Vouch For.',
    galleryEy: 'Inside the clinic', galleryTitle: 'Step Into a Space Designed for Healing.',
    gallerySub: 'Modern, calming and immaculately clean — see where your recovery happens.',
    bookEy: 'One conversation away', bookTitle: 'Let’s Take the First Step Together.',
    bookBody: 'Booking an appointment is simple. Choose your preferred date and our team will contact you to confirm the exact time and provide any additional information you need.',
    locEy: 'Visit us', locTitle: 'Find Core Physio Clinic.',
    addressLabel: 'Address', hoursLabel: 'Working Hours', phoneLabel: 'Phone',
    address: ['Twin Towers Mall', 'Second Al Sheikh Zayed', 'Giza Governorate 12511, Egypt'],
    hours: [['Saturday – Thursday', '9:00 AM – 10:00 PM'], ['Friday', 'Closed']],
    finalEy: 'Start your journey today', finalTitle: 'Because Living Without Pain Changes Everything.',
    finalSub: 'Experience professional physiotherapy care in a trusted and welcoming environment.',
    footerTag: 'Move Better. Live Pain Free.',
    quickLinks: 'Quick Links', contact: 'Contact', follow: 'Follow Us',
    rights: '© 2026 Core Physio Clinic. All Rights Reserved.',
    openNow: 'Open now',
  },
  ar: {
    book: 'احجز موعدك', whatsapp: 'تواصل عبر واتساب', call: 'اتصل الآن', directions: 'احصل على الاتجاهات',
    bookCta: 'احجز عبر واتساب', learn: 'اعرف المزيد',
    ratingLabel: 'تقييم جوجل', reviewsLabel: 'آراء المرضى',
    heroBadge: 'علاج طبيعي وتأهيل · الشيخ زايد',
    heroTitle: 'رحلتك نحو حياة بلا ألم تبدأ من هنا.',
    heroSub: 'رعاية علاج طبيعي وتأهيل احترافية في الشيخ زايد، مصمّمة لمساعدتك على الحركة بشكل أفضل والتعافي أسرع واستعادة الثقة في حياتك اليومية.',
    trust1: 'رعاية تأهيل احترافية', trust2: 'تقنيات علاج حديثة',
    statPatients: 'مريض سعيد', statOwned: 'عيادة تديرها سيدات', statLocated: 'في الشيخ زايد', statRating: 'تقييم',
    empathyEy: 'نتفهّم ما تمرّ به', empathyTitle: 'العيش مع الألم لا يجب أن يكون حياتك الجديدة.',
    empathyBody: 'سواء كنت تعاني من آلام الظهر أو الرقبة أو إصابات رياضية أو مشاكل في وضعية الجسم أو محدودية في الحركة، فإن هذه التحديات تؤثر على كل جانب من حياتك اليومية. في كور فيزيو نؤمن أن التعافي أكثر من مجرد علاج الألم — إنه استعادة لجودة حياتك.',
    pains: ['آلام الظهر والرقبة', 'الإصابات الرياضية', 'مشاكل وضعية الجسم', 'محدودية الحركة', 'التعافي بعد الجراحة', 'التيبّس المزمن'],
    aboutEy: 'تعرّف على العيادة', aboutTitle: 'مكان مصمّم حول تعافيك.',
    aboutBody: 'داخل تُوين تاورز مول في الشيخ زايد، توفّر عيادة كور فيزيو بيئة حديثة ومريحة ومرحّبة، يتلقّى فيها المرضى خطط علاج مخصّصة باستخدام تقنيات علاج طبيعي قائمة على الأدلة.',
    aboutFeat: ['عيادة تديرها سيدات', 'أجواء مريحة', 'منهج تأهيل حديث', 'رعاية تتمحور حول المريض'],
    trustEy: 'لماذا يثق بنا المرضى', trustTitle: 'محل ثقة المرضى في الشيخ زايد.',
    trustSub: 'سمعة بُنيت على نتائج حقيقية ورعاية صادقة وعيادة نظيفة ومرحّبة.',
    trustItems: [
      { icon: 'star', t: 'تقييم 4.9 على جوجل', d: 'تقييم 4.9 من 5 عبر أكثر من 35 مراجعة موثّقة.' },
      { icon: 'users', t: 'فريق محترف', d: 'أخصائيو علاج طبيعي ذوو خبرة يركّزون على التعافي طويل المدى.' },
      { icon: 'sparkles', t: 'مرافق نظيفة', d: 'نظافة وتنظيم وأجواء مرحّبة في كل ركن.' },
      { icon: 'heart', t: 'بيئة ودودة', d: 'رعاية دافئة وداعمة من أول زيارة.' },
      { icon: 'clipboard-list', t: 'علاجات مخصّصة', d: 'كل خطة مصمّمة حسب جسمك وأهدافك.' },
      { icon: 'shield-check', t: 'رعاية قائمة على الأدلة', d: 'تقنيات تأهيل حديثة ومثبتة.' },
    ],
    journeyEy: 'كيف نساعدك على التعافي', journeyTitle: 'التعافي رحلة، ونحن نرشدك في كل خطوة.',
    journeySub: 'مسار واضح وداعم من أول تقييم وحتى عودتك الكاملة للحياة اليومية.',
    servicesEy: 'خدماتنا المتخصّصة', servicesTitle: 'رعاية لكل مرحلة من رحلة تعافيك.',
    servicesSub: 'من تخفيف الألم الحاد إلى الأداء طويل المدى — علاج طبيعي شامل تحت سقف واحد.',
    reviewsEy: 'قصص حقيقية من مرضى حقيقيين', reviewsTitle: 'تعافٍ تشعر به — ويشهد به المرضى.',
    galleryEy: 'داخل العيادة', galleryTitle: 'ادخل إلى مكان مصمّم للشفاء.',
    gallerySub: 'حديث وهادئ ونظيف تمامًا — شاهد أين يحدث تعافيك.',
    bookEy: 'محادثة واحدة تفصلك', bookTitle: 'لنأخذ الخطوة الأولى معًا.',
    bookBody: 'حجز موعدك بسيط. اختر التاريخ المناسب لك وسيتواصل معك فريقنا لتأكيد الوقت بالضبط وتقديم أي معلومات إضافية تحتاجها.',
    locEy: 'زورونا', locTitle: 'كيف تصل إلى كور فيزيو.',
    addressLabel: 'العنوان', hoursLabel: 'ساعات العمل', phoneLabel: 'الهاتف',
    address: ['تُوين تاورز مول', 'الشيخ زايد الثانية', 'محافظة الجيزة 12511، مصر'],
    hours: [['السبت – الخميس', '9:00 ص – 10:00 م'], ['الجمعة', 'مغلق']],
    finalEy: 'ابدأ رحلتك اليوم', finalTitle: 'لأن الحياة بلا ألم تغيّر كل شيء.',
    finalSub: 'اختبر رعاية علاج طبيعي احترافية في بيئة موثوقة ومرحّبة.',
    footerTag: 'تحرّك أفضل. عِش بلا ألم.',
    quickLinks: 'روابط سريعة', contact: 'تواصل', follow: 'تابعنا',
    rights: '© 2026 عيادة كور فيزيو. جميع الحقوق محفوظة.',
    openNow: 'مفتوح الآن',
  },
};

Object.assign(window, { NAV, SERVICES, STEPS, REVIEWS, GALLERY, T });
